openapi: 3.0.1
info:
  title: Interface [[${entityName}]]
  description: Interface pour la gestion des [[${description}]]
  version: 1.0.0
tags:
  - name: [[${entityName}]]
    description: [[${description}]]
paths:
  /v1/[[${entityName.toLowerCase()}]]s:
    get:
      tags:
        - [[${entityName}]]
      operationId: getAll
      summary: "Obtenir les [[${description}]] par société"
      description: "Récupère une liste de [[${description}]] associée à une société spécifique."
      parameters:
        - in: header
          name: idCompany
          required: true
          schema:
            type: integer
          description: "Identifiant de la société"
      responses:
        '200':
          description: "Liste des [[${description}]] récupérée avec succès"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/[[${entityName}]]'

    post:
      tags:
        - [[${entityName}]]
      operationId: postAll
      summary: "Créer des [[${description}]]"
      description: "Ajoute une liste de [[${description}]]."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/[[${entityName}]]'
      responses:
        '201':
          description: "Liste des [[${description}]] créée avec succès"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/[[${entityName}]]'
        '406':
          description: Not Acceptable

    put:
      tags:
        - [[${entityName}]]
      operationId: putAll
      summary: "Mettre à jour la liste des [[${description}]]"
      description: "Met à jour une liste de [[${description}]] existante."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/[[${entityName}]]'
      responses:
        '202':
          description: "Liste des [[${description}]] mise à jour avec succès"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/[[${entityName}]]'
        '406':
          description: Not Acceptable

    delete:
      tags:
        - [[${entityName}]]
      operationId: deleteAll
      summary: "Supprimer la liste des [[${description}]]"
      description: "Supprime une liste de [[${description}]]."
      responses:
        '204':
          description: "Liste des [[${description}]] supprimée avec succès"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/[[${entityName}]]'
        '406':
          description: Not Acceptable

components:
  schemas:
    [[${entityName}]]:
      type: object
      required:
        - id
      properties:
        id:
  [[${embeddedProperty}]]
  [[${entityName}]]Id:
                     type: object
                     properties:
                       idCompany:
                         type: integer
                         description: "Identifiant de la société"
